### ISSUE TITLE
Error in Version Comunity edition

### ISSUE THREAD

**Issue by criszalo1997** [jogetoss/echart-menu#1]
hello developer i have been trying to use your plugin for joget and i run into this problem when installing it in the community edition version it shows me unrecognizable characters

![image](https://user-images.githubusercontent.com/29022806/166105865-81163b4e-e76c-485d-9f46-7fb9331b3e4c.png)

**Comment by hugoatjoget** [comment]
Thanks for reporting this. This plugin is classified to only work with Professional and Enterprise and above. See https://marketplace.joget.org/jw/web/userview/mp/mpp/_/vad?id=echart_plugin
